FROM python:3.10

WORKDIR /app

# Copy required files to the environement.
# COPY ../api/src /app/src
# COPY ../configs /app/configs
COPY ../requirements.txt /app

RUN apt update
RUN apt upgrade -y
RUN pip install --upgrade pip
RUN pip install -r requirements.txt

EXPOSE 8000

CMD ["uvicorn", "src.app:fastapi_app", "--reload", "--host", "0.0.0.0", "--port", "8000"]